### ISSUE TITLE
field names are missing

### ISSUE THREAD

**Issue by OriHoch** [CIOIL/GuideStar#2]
In many places of the code it appears that field names were replaced by `field`

for example:

https://github.com/CIOIL/GuideStar/blob/master/Guidestar%20Server%20Side/classes/GSTAR_Ctrl_Meta.cls#L50

field names are crucial for understanding the code are should not cause security or privacy concerns

**Comment by shmuelna** [comment]
According to the data security procedure in government offices, it is forbidden to publish field names in Data Base, so every place where field name or object name appears, it's been replaced
