### ISSUE TITLE
should have an index of redacted details

### ISSUE THREAD

**Issue by OriHoch** [CIOIL/GuideStar#4]
It seems some details were redacted from the code, it would be helpful to have a list of all the redacted details and reasons for reduction to get a better understanding of the code. Currently it's very hard to know how the redacted details interact with the rest of the code and logic.

**Comment by shmuelna** [comment]
According to the data security procedure in government offices, it is forbidden to publish field names in Data Base, so every place where field name or object name appears, it's been replaced
